// ESLint flat config for browser-based linting (ESLint 9+)
export const eslintConfig = {
  languageOptions: {
    ecmaVersion: 2020,
    sourceType: "module",
    parserOptions: {
      ecmaFeatures: {
        jsx: true,
      },
    },
    globals: {
      // Browser globals
      window: "readonly",
      document: "readonly",
      console: "readonly",
      setTimeout: "readonly",
      setInterval: "readonly",
      clearTimeout: "readonly",
      clearInterval: "readonly",
      Promise: "readonly",
      fetch: "readonly",
      localStorage: "readonly",
      sessionStorage: "readonly",
      navigator: "readonly",
      location: "readonly",
      history: "readonly",
      alert: "readonly",
      confirm: "readonly",
      prompt: "readonly",
      // Common globals
      Array: "readonly",
      Object: "readonly",
      String: "readonly",
      Number: "readonly",
      Boolean: "readonly",
      Date: "readonly",
      Math: "readonly",
      JSON: "readonly",
      RegExp: "readonly",
      Error: "readonly",
      Map: "readonly",
      Set: "readonly",
      WeakMap: "readonly",
      WeakSet: "readonly",
      Symbol: "readonly",
      Proxy: "readonly",
      Reflect: "readonly",
      // Timers
      requestAnimationFrame: "readonly",
      cancelAnimationFrame: "readonly",
      requestIdleCallback: "readonly",
      cancelIdleCallback: "readonly",
      // Additional browser APIs
      CustomEvent: "readonly",
      Event: "readonly",
      EventTarget: "readonly",
      HTMLElement: "readonly",
      NodeList: "readonly",
      Element: "readonly",
      Response: "readonly",
      Request: "readonly",
      URL: "readonly",
      URLSearchParams: "readonly",
      FormData: "readonly",
      Blob: "readonly",
      File: "readonly",
      FileReader: "readonly",
      AbortController: "readonly",
      AbortSignal: "readonly",
    },
  },
  rules: {
    // Possible Errors
    "no-cond-assign": "error",
    "no-console": "off",
    "no-constant-condition": "warn",
    "no-debugger": "warn",
    "no-dupe-args": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "warn",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "warn",
    "no-extra-semi": "error",
    "no-func-assign": "error",
    "no-inner-declarations": "warn",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-obj-calls": "error",
    "no-sparse-arrays": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "warn",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "use-isnan": "error",
    "valid-typeof": "error",

    // Best Practices
    curly: ["warn", "multi-line"],
    eqeqeq: ["error", "always", { null: "ignore" }],
    "no-caller": "error",
    "no-else-return": "warn",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "warn",
    "no-fallthrough": "warn",
    "no-floating-decimal": "error",
    "no-implied-eval": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "warn",
    "no-loop-func": "error",
    "no-multi-spaces": "warn",
    "no-new": "warn",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-proto": "error",
    "no-redeclare": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unused-expressions": [
      "error",
      { allowShortCircuit: true, allowTernary: true },
    ],
    "no-useless-call": "warn",
    "no-useless-concat": "warn",
    "no-useless-escape": "warn",
    "no-void": "error",
    "no-with": "error",
    radix: "warn",
    "wrap-iife": ["error", "any"],

    // Variables
    "no-delete-var": "error",
    "no-shadow-restricted-names": "error",
    "no-undef": "error",
    "no-undef-init": "warn",
    "no-unused-vars": ["warn", { vars: "all", args: "none" }],
    "no-use-before-define": [
      "error",
      { functions: false, classes: true, variables: true },
    ],

    // Stylistic Issues
    "array-bracket-spacing": ["warn", "never"],
    "block-spacing": ["warn", "always"],
    "brace-style": ["warn", "1tbs", { allowSingleLine: true }],
    "comma-spacing": ["warn", { before: false, after: true }],
    "comma-style": ["warn", "last"],
    "computed-property-spacing": ["warn", "never"],
    "eol-last": ["warn", "always"],
    "func-call-spacing": ["warn", "never"],
    "key-spacing": ["warn", { beforeColon: false, afterColon: true }],
    "keyword-spacing": ["warn", { before: true, after: true }],
    "linebreak-style": ["warn", "unix"],
    "new-parens": "error",
    "no-array-constructor": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multiple-empty-lines": ["warn", { max: 2, maxEOF: 0 }],
    "no-new-object": "error",
    "no-tabs": "error",
    "no-trailing-spaces": "warn",
    "object-curly-spacing": ["warn", "always"],
    semi: ["error", "always"],
    "semi-spacing": ["warn", { before: false, after: true }],
    "space-before-blocks": ["warn", "always"],
    "space-before-function-paren": [
      "warn",
      { anonymous: "always", named: "never", asyncArrow: "always" },
    ],
    "space-in-parens": ["warn", "never"],
    "space-infix-ops": "warn",
    "space-unary-ops": ["warn", { words: true, nonwords: false }],

    // ES6
    "arrow-spacing": ["warn", { before: true, after: true }],
    "constructor-super": "error",
    "no-class-assign": "error",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": "warn",
    "no-new-symbol": "error",
    "no-this-before-super": "error",
    "no-var": "warn",
    "prefer-const": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "require-yield": "error",
  },
};
